### PR TITLE
Work pages

### PR DESCRIPTION
**Pull request by nmorduch**
Show services and technologies on work page and individual case studies.

### CODE REVIEW

**Comment by harrislapiroff** [comment]
Technically everything here looks good. I have some minor design concerns that I'm happy to be overridden on, mostly.

screen shot 2016-06-22 at 12 17 03 pm

At least with the content we have in the DB currently, the list of services looks pretty dense and unfriendly in this design. The solution might not be part of this PR and might be just to have more human-friendly names for the services ("Custom CMS" instead of "Backend Development" and "Frontend Development") but I also feel like part of the trouble is that the all capsing and heavier font weight makes it feel like these are _more_ important than the description. I think they're more like tags; they should be available but not begging to be read.

screen shot 2016-06-22 at 12 21 12 pm

This is a lot of type treatments in three lines and the spacing is a little weird. The second line feels closer to the third than the first, should be more equidistant. Do we need all three headings though? Maybe just one of the headings and the client name is enough?

screen shot 2016-06-22 at 12 23 01 pm

Same issue as the listing on the list page. Also we might need a "Technologies" label because otherwise this will look like a confusing gibberish list to most users. Also the bird is too close.

**Comment by harrislapiroff** [comment]
I'm happy to take a stab at some fixes myself, if there's agreement on my assessment. It might take me a minute to get around to though.

**Comment by melinath** [comment]
I think the "fun" description was supposed to be displayed as the caption for the image on the detail page.

**Comment by nmorduch** [comment]
@melinath after looking at it, this seemed to work better. open for discussion tho


@harrislapiroff:

this was definitely one i wanted your design eye on, v much appreciating feeback.

- there is intentionally spacing btwn list items, to separate them. the whole thing could definitely use more space though.
- you're right that the bird is too close. not really sure how to fix it without rewriting the whole header. which maybe we should do?
- 👍 technologies header
- maybe we should use shorter titles? smaller text seems dangerous. i really like having them in a sidebar. would be down with left-aligning if you think that would be better.

**Comment by harrislapiroff** [comment]
- Spacing around the titles is weird, not the list items. List item spacing is fine.
- There's no real reason the list items need to line up with the screenshot, is there? We can just bump them down below the birb. Or if we want them to line up with something, line them up with the text after the screenshot?
- Def not smaller text. I'm thinking some combination of: lighter weight, lighter color (have to see if we run aground on color contrast), and not all caps

**Comment by nmorduch** [comment]
👍 to all @harrislapiroff

**Comment by nmorduch** [comment]
Ok try again :)

**Comment by harrislapiroff** [comment]
It looks fairly strange with just single items, but maybe that won't be a real-world issue.

screenshot 2016-08-12 16 56 40

**Comment by harrislapiroff** [comment]
Good enough for government work, though.

**Comment by harrislapiroff** [comment]
(Just kidding, we can't get government work)

**Pull request merged**
