### PR TITLE
Added banner images to author pages

### PR DESCRIPTION
**Pull request by cheryllium**
Merge this into author-pages instead as it is based on this branch.

### CODE REVIEW

**Comment by nmorduch** [comment]
@cheryllium you need a migration

**Comment by cheryllium** [comment]
@nmorduch What do you mean? Do you mean I'm supposed to commit the migration made by manage.py makemigrations?

**Comment by nmorduch** [comment]
Yes! You should always commit the migrations too.

**Comment by cheryllium** [comment]
@nmorduch Migration added! (Also added a migration to author-pages, both branches should be good now.)

**Pull request merged**
