### PR TITLE
Update favicon with rounded corners

### PR DESCRIPTION
**Pull request by harrislapiroff**
Make favicon retina-friendly and kid-safe

### CODE REVIEW

**Comment by harrislapiroff** [comment]
Assigning @melinath because I don't know for sure if this is all I need to do to deploy a new favicon

**Comment by harrislapiroff** [comment]
Pinging @melinath

**Comment by melinath** [comment]
@harrislapiroff why does this have the jobs adding to nav in it?

**Comment by harrislapiroff** [comment]
Hrmph. I must have based it off the wrong branch. :\

**Comment by melinath** [comment]
okay so it's just the last commit. I'll fix the branch.

**Comment by harrislapiroff** [comment]
thaaaaanks <3

**Comment by melinath** [comment]
Okay, so there are a bunch of different favicons that we have that are used for different things. These files are all in https://github.com/littleweaver/littleweaverweb.com/tree/master/core/static/img/favicons.  This only touches one of those files. Do the other ones not need to be updated? Also, what is this icons.iconsproj file and why is it in a different location?

The files were generated with http://realfavicongenerator.net/. According to their config checker the conf needs to be updated to serve the files from a root url - so that should probably be fixed too.

**Comment by harrislapiroff** [comment]
Reasonable points. I'll look into realfavicongenerator. I've heard good things. I admit to being skeptical of automated favicon generators because I think it's pretty important to be fairly precise with the pixels of your icon, since you're working at such low pixel density. And also because the automated generator gives us results like

screenshot 2016-08-16 23 18 45

which is not super great. I used [Icon Slate](https://www.google.com/search?q=icon+slate&ie=utf-8&oe=utf-8) to build the icons which lets you specify a different image for each icon and size.

I think most of the OS icons don't need to be updated because most OSes control the shape of app icons themselves? I'll look at what else is in there. Also the rounded corners idea was specific to what looks good in a web browser tab.

**Comment by melinath** [comment]
Closing this PR - I don't think we're going to get to it.

**Pull request closed without merging**
