### PR TITLE
Autoprefixer

### PR DESCRIPTION
**Pull request by melinath**
Adds autoprefixer support to compressor.

### CODE REVIEW

**Comment by harrislapiroff** [comment]
A few questions/concerns:

1. I'm not sure this is working. Not all prefix-requiring declarations seem to be prefixed on my local machine. Maybe because django-compressor-autoprefixer doesn't know where the binary is?
2. I actually suspect django-compressor-autoprefixer is an unnecessary and confusing intermediary. It doesn't do anything but run the autoprefixer binary. We could just do that ourselves.
3. You should confirm, once it's working, that it's not adding too much time to loads. This is less important (but still a bit important) if the answer to 4 is yes:
4. Are we precompressing upon deployment?

**Comment by melinath** [comment]
1. It is working, assuming you have compress enabled. But autoprefixer only supports the previous two versions of browsers by default, so you may not be seeing some prefixes you'd expect.
2. Yes, it's a simple class that we could implement ourselves, but I think that would ultimately be more confusing than using the version someone else already packaged nicely for us.
3 & 4. We're compressing on deployment.

**Comment by emilyhorsman** [comment]
I would highly recommend we set the browser versions in autoprefixer, https://github.com/twbs/bootstrap/blob/v4.0.0-alpha.2/Gruntfile.js#L24

**Comment by harrislapiroff** [comment]
1. Oops, you're right.
2. I actually think it would be less confusing if we implemented it ourselves because the code would be immediately accessible to us. And I hate depending on packages that have such tiny GitHub presences. (13 stars????) Literally anything could happen to that package. But I'm basically OK with this if you are.

Basically OK to merge, maybe with input from Emily on browser versions.

**Pull request merged**
