### PR TITLE
change bg color to footer color

### LINKED ISSUE #68: Services page background
On (much) larger monitors, the technology and service block does not reach all the way down. This leaves a white gap between the content and footer.

### PR DESCRIPTION
**Pull request by nmorduch**
closes #68

### CODE REVIEW

**Comment by harrislapiroff** [comment]
This looks pretty good, if a little odd if the display is long and/or the page is short. I wonder if a better solution in the future might just be to abandon the sticky footer.

screen shot 2016-06-22 at 12 02 01

Merging for now, though.

**Comment by nmorduch** [comment]
oops yeah we should also abandon the sticky footer. i would never have written it tbh

**Comment by harrislapiroff** [comment]
you must be a better designer than me ¯\_(ツ)_/¯

**Comment by nmorduch** [comment]
no i mean it's a good _design_ idea, it's just messy to execute, i think. lots of edge cases. i would never have written it because i am lazy.

**Pull request merged**
