### PR TITLE
Vertically center header items to make content flush with each other

### PR DESCRIPTION
**Pull request by emilyhorsman**
Addresses #37.

screen shot 2016-02-26 at 9 23 12 pm

screen shot 2016-02-26 at 9 23 02 pm

### CODE REVIEW

**Comment by nmorduch** [comment]
Hmmm I'd prefer a solution that does not require pixel heights. Thoughts?

**Comment by emilyhorsman** [comment]
All depends if we want to chop up the markup or not, we could use `display: table-row` and `display: table-cell` with `vertical-align: middle` which would work nicely, but requires changing the markup in a way that is not very correct, semantically. However, we could also use JS to dynamically determine a suitable pixel height. Totally agreed that setup heights here are not the best.

**Comment by nmorduch** [comment]
I think using table-row would not be semantically the worst? Since we are indeed making a table here, just one that we don't display as a table on narrow screens. I think it is about as legit as using table markup and displaying not-as-a-table on narrow screens. Not sure if that is too meandering but it boils down to I think that is a good idea. Though does it get complicated when it goes to 2x2 instead of 1x4?

**Comment by harrislapiroff** [comment]
I don't think the question is the semantics of using a `<table>` since using `display: table-row` in CSS has no semantic meaning. (Since CSS is generally not considered to have semantic meaning, except for, like, aural CSS.) I think Emily is saying that she would have to restructure the HTML so that all the headings came first in one group and then the paragraphs next in another group. Which would be very unpleasant if, for instance, you were on a screen reader or a narrow screen. Is that right, @emilyhorsman?

I agree that neither that nor the static heights in the PR are ideal...

**Comment by harrislapiroff** [comment]
CSS3 grid layouts will arrive some happy day, eh?

**Comment by nmorduch** [comment]
I'm feeling like we should merge this and have a new issue for a more flexible solution. @harrislapiroff ?

**Comment by emilyhorsman** [comment]
Yes, using the CSS property has no semantic meaning, so that's fine. It would require changing markup in the manner @harrislapiroff describes though, which is semantically problematic.

A common solution to this is setting a reasonable guess with CSS and then computing something proper with JavaScript. I think this is fine if this is done in by progressive enhancement, it's common. (I used to cringe at using JS for anything layout but various past work has kinda knocked that out of me.)

**Comment by nmorduch** [comment]
I'll defer to you two :)

**Comment by emilyhorsman** [comment]
If there's no cross-browser issues with the current solution then I would :+1: merging this with a future, more robust/perfect solution.

I would also recommend @emilyhorsman quit using the word “robust” quite so much.

**Pull request merged**
