### PR TITLE
Improved Testimonials and Quotes (work in progress)

### PR DESCRIPTION
**Pull request by chigby**
Addresses #45.

### CODE REVIEW

**Comment by nmorduch** [comment]
Is this not ready for styling? I got `Unknown field(s) (testimonial_credit, testimonial) specified for WorkPage`

**Comment by chigby** [comment]
Oh, the FieldPanel is still there. I can delete that, too.

**Comment by nmorduch** [comment]
This has conflicts with #44. I would do that one first, then this one, I think.

**Comment by nmorduch** [comment]
But this is good. I would merge this after addressing conflicts :)

**Comment by nmorduch** [comment]
Also worth noting: We're currently using quotes as image captions, and my styles for actual quotes would break this. Let's get a caption field added to the image block, too.

**Comment by chigby** [comment]
@nmorduch Okay, I pushed a migration that should:

1. Set the blog and work pages to use captioned images.
2. Convert all old images into captioned images.

Let me know if this works when you migrate.

**Pull request merged**
